// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPpllk7zHML7DtKdDk7g0RPeeQ-aTsT74',
    appId: '1:43509276428:web:7ab23ede6e656d2b09b329',
    messagingSenderId: '43509276428',
    projectId: 'smartsan-00',
    authDomain: 'smartsan-00.firebaseapp.com',
    storageBucket: 'smartsan-00.firebasestorage.app',
    measurementId: 'G-3SZ7Y4WRME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjo8T-vvhR5eh0wMyYfS1qTNAzKk2-XYE',
    appId: '1:43509276428:android:1d53824ab4c5a84909b329',
    messagingSenderId: '43509276428',
    projectId: 'smartsan-00',
    storageBucket: 'smartsan-00.firebasestorage.app',
  );

}